#ifndef WINDOW_CONSTANT_H
#define WINDOW_CONSTANT_H

const int MAP_TILE_SIZE = 44;
const int MAP_ROW_COUNT = 15;
const int MAP_COL_COUNT = 25;

const int WINDOW_WIDTH = MAP_TILE_SIZE*MAP_COL_COUNT;
const int WINDOW_HEIGHT = MAP_TILE_SIZE*MAP_ROW_COUNT;

#endif // WINDOW_CONSTANT_H
